### ISSUE TITLE
Pressing tab to hide side bar causes exception when opengl mode is active

### ISSUE THREAD

**Issue by VorpalBlade** [michaelzangl/josm-plugin-opengl#10]
When OpenGL mode is active an exception is caused by hitting tab to hide the side bar. Below is the debug data from the exception.

This happens on Debian 7.9 (wheezy, x86_64, yes I need to update soonish).
GPU is an AMD Radeon HD 6850 (using catalyst drivers, not the open drivers).

```
Repository Root: http://josm.openstreetmap.de/svn
Build-Date: 2015-08-21 23:32:08
Last Changed Author: Don-vip
Revision: 8677
Repository UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Relative URL: ^/trunk
URL: http://josm.openstreetmap.de/svn/trunk
Last Changed Date: 2015-08-21 22:18:03 +0200 (Fri, 21 Aug 2015)
Last Changed Rev: 8677

Identification: JOSM/1.5 (8677 en) Linux Debian GNU/Linux 7.9 (wheezy)
Memory Usage: 1557 MB / 3568 MB (1113 MB allocated, but free)
Java version: 1.7.0_79, Oracle Corporation, OpenJDK 64-Bit Server VM
Java package: openjdk-7-jre:amd64-7u79-2.5.6-1~deb7u1
VM arguments: [-Djosm.restart=true, -Djava.net.useSystemProxies=true]
Dataset consistency test: No problems found

Plugins:
- AddrInterpolation (31241)
- HouseNumberTaggingTool (31241)
- OpeningHoursEditor (31241)
- alignways (31241)
- buildings_tools (31361)
- commons-imaging (31241)
- ext_tools (31241)
- geotools (31126)
- gpsblam (31241)
- gpxfilter (31241)
- graphview (31241)
- imagery_offset_db (31241)
- josm-plugin-opengl (1440156917)
- jts (31126)
- opendata (31241)
- rasterfilters (31509)
- terracer (31241)
- turnlanes (31241)
- turnrestrictions (31241)
- utilsplugin2 (31463)

Last errors/warnings:
- W: No style set for {Node id=1736498919 version=1 V lat=59.2490058,lon=15.1439163}
- W: No style set for {Node id=1736498866 version=1 V lat=59.2478208,lon=15.1428727}
- E: java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
- E: java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
- E: java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location

java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
    at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2048)
    at java.awt.Component.getLocationOnScreen(Component.java:2022)
    at org.openstreetmap.josm.gui.MapView.rememberLastPositionOnScreen(MapView.java:352)
    at org.openstreetmap.josm.actions.DialogsToggleAction.setMode(DialogsToggleAction.java:65)
    at org.openstreetmap.josm.actions.DialogsToggleAction.actionPerformed(DialogsToggleAction.java:42)
    at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1662)
    at javax.swing.JComponent.processKeyBinding(JComponent.java:2870)
    at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
    at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:263)
    at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2962)
    at javax.swing.JComponent.processKeyBindings(JComponent.java:2954)
    at javax.swing.JComponent.processKeyEvent(JComponent.java:2833)
    at java.awt.Component.processEvent(Component.java:6293)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887)
    at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762)
    at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
    at java.awt.Component.dispatchEventImpl(Component.java:4742)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:720)
    at java.awt.EventQueue$4.run(EventQueue.java:718)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by michaelzangl** [comment]
Same cause as #9
